name: bookify
description: BOOKIFY - Your Premium Book Store.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  # Backend
  supabase_flutter: ^2.0.2
  
  # Navigation & UI
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  
  # Utils
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
  web:
    generate: true
    image_path: "assets/images/app_icon.jpg"
  windows:
    generate: true
    image_path: "assets/images/app_icon.jpg"
  macos:
    generate: true
    image_path: "assets/images/app_icon.jpg"
  linux:
    generate: true
    image_path: "assets/images/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
